### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by mushan-guan** [chenhcs/scResolve#3]
When I used `scResolve convert visium` function, I encountered the following issue.

```
(env_scresolve) root@share-gxe8i6thv0:~# scresolve convert visium \
 --bc-matrix ./filtered_feature_bc_matrix.h5 \
 --image ./tissue_hires_image.png \
 --tissue-positions ./tissue_positions_list.csv \
 --scale-factors ./scalefactors_json.json \
 --mask-file ./detected_tissue_image.jpg \
 --scale 1 \
 --save-path ./out
/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/spaghetti/network.py:40: FutureWarning:

The next major release of pysal/spaghetti (2.0.0) will drop support for all ``libpysal.cg`` geometries. This change is a first step in refactoring ``spaghetti`` that is expected to result in dramatically reduced runtimes for network instantiation and operations. Users currently requiring network and point pattern input as ``libpysal.cg`` geometries should prepare for this simply by converting to ``shapely`` geometries.

/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning:

Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.9.0 and strictly below 2.12.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.8.2 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons

[2024-10-17 10:45:40,259] ℹ : Running scresolve version 0.1.0
[2024-10-17 10:45:42,676] 🚨 ERROR : TypeError: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 165, in _na_arithmetic_op
    result = func(left, right)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 241, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 129, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/scresolve/__main__.py", line 83, in _wrapped
    return f(*args, **kwargs)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/scresolve/__main__.py", line 171, in _convert_visium
    convert.visium.run(
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/scresolve/convert/visium.py", line 58, in run
    tissue_positions[["x", "y"]] *= scale_factor
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/generic.py", line 12104, in __imul__
    return self._inplace_method(other, type(self).__mul__)  # type: ignore[operator]
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/generic.py", line 12073, in _inplace_method
    result = op(self, other)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/ops/common.py", line 72, in new_method
    return method(self, other)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/arraylike.py", line 118, in __mul__
    return self._arith_method(other, operator.mul)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/frame.py", line 7594, in _arith_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/frame.py", line 7621, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 350, in apply
    applied = b.apply(f, **kwargs)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 351, in apply
    result = func(self.values, **kwargs)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 226, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 172, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/root/mambaforge/envs/env_scresolve/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 129, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: can't multiply sequence by non-int of type 'float'

```

This is the head of `tissue_positions_list.csv`
```
barcode,in_tissue,array_row,array_col,pxl_row_in_fullres,pxl_col_in_fullres
GTCACTTCCTTCTAGA-1,0,0,0,782,311
CACGGTCTCCTTACGA-1,0,0,2,782,332
ATAGCTGCGGATAAGA-1,0,0,4,782,354
GTCAGTATGTCCGGCG-1,0,0,6,782,375
ATGTACCAGTTACTCG-1,0,0,8,782,397
ACGCTCAGTGCACCGT-1,0,0,10,782,418
TCACTAACGTATAGTT-1,0,0,12,783,440
CGGTTAGGCCTGGACG-1,0,0,14,783,461
GATATCACCAGCATGG-1,0,0,16,783,483
```

Thanks!

**Comment by NKalavros** [comment]
Make sure your file has no header! You can achieve this with something like the following:

From the spaceranger output folder:
```
sed '1d' $(pwd)/spatial/tissue_positions.csv > $(pwd)/spatial/tissue_positions_list.csv
```
